language: cpp
compiler: 
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - xorg-dev
    - libglu1-mesa-dev
    - clang-3.5
script:
  - cmake -G "Unix Makefiles" -DEQEMU_ENABLE_GL=ON
  - make -j8
notifications:
  email: false
  irc:
    channels: "irc.eqemulator.net#eqemucoders"
os: linux
