language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - xorg-dev
    - libglu1-mesa-dev
    - libbullet-dev
    - libglew-dev
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.sh
  - chmod +x cmake-3.11.2-Linux-x86_64.sh
  - ./cmake-3.11.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
script:
  - cmake -G "Unix Makefiles" -DEQEMU_ENABLE_GL=ON
  - make -j8
notifications:
  email: false
os: linux
