language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.sh
  - chmod +x cmake-3.11.2-Linux-x86_64.sh
  - ./cmake-3.11.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
install:
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install xorg-dev
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libbullet-dev
  - sudo apt-get install libglew-dev
script:
  - cmake -G "Unix Makefiles" -DEQEMU_ENABLE_GL=ON
  - make -j8
