language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y zlib1g-dev xorg-dev libglu1-mesa-dev
script:
  - cmake -G "Unix Makefiles" -DEQEMU_ENABLE_GL=ON
  - make
branches:
  only: master
notifications:
  email: false
  irc:
    channels: "irc.eqemulator.net#eqemucoders"
os: linux