language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - xorg-dev
    - libglu1-mesa-dev
    - libbullet-dev
    - libglew-dev
script:
  - cmake -G "Unix Makefiles" -DEQEMU_ENABLE_GL=ON
  - make -j8
notifications:
  email: false
os: linux
