version: 2.0.{build}

image:
  - Visual Studio 2022
  - Ubuntu

platform: x64
configuration: Release

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

clone_folder: c:\projects\zone-utilities

install:
- git submodule update --init
- cmd: set PATH=C:\ninja;%PATH%

build_script:
- cmd: mkdir build_windows
- cmd: cd build_windows
- cmd: cmake -GNinja -DEQEMU_ENABLE_GL=ON ..
- cmd: ninja
- sh: mkdir build_linux
- sh: cd build_linux
- sh: cmake -GNinja -DEQEMU_ENABLE_GL=ON ..
- sh: ninja
