FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04
RUN sudo apt update && \
	sudo apt install -y \
	--no-install-recommends \
	build-essential libtool cmake curl debconf-utils \
	git liblua5.1-0 liblua5.1-0-dev libluabind-dev \
	libmysql++-dev libsodium-dev \
	libmysqlclient-dev libssl-dev lua5.1 minizip make mariadb-client locales \
	nano open-vm-tools unzip uuid-dev iputils-ping wget libcurl4-openssl-dev gdb \
	libyaml-cpp-dev libgtest-dev pkg-config libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev libxmu-dev libxi-dev libgl-dev